### Send POST request with json body
POST http://localhost:9090/questions
Content-Type: application/json

{
  "title": "new record3",
  "description": "testing record3"
}

### Send POST request with json body
POST http://localhost:9090/questions/10/comments
Content-Type: application/json

{
  "comment": "test comment77"
}

### Send DELETE request
DELETE http://localhost:9090/questions/10/comments/45
Content-Type: application/json

### Send PUT request
PUT http://localhost:9090/questions
Content-Type: application/json

{
  "id": 10,
  "title": "новая работа",
  "description": "пахать когда можно уже"
}

### Send PUT request
PUT http://localhost:9090/questions/comments
Content-Type: application/json

{
  "id": 7,
  "comment": "checking"
}

###





