### Send POST request with json body
POST http://localhost:9090/questions
Content-Type: application/json

{
  "title": "вопрос 5",
  "description": "вопрос номер 5 в схеме stack"
}

### Send POST request with json body
POST http://localhost:9090/questions/4/comments
Content-Type: application/json

{
  "comment": "тест коммент 44444444"
}

### Send DELETE request
DELETE http://localhost:9090/questions/2
Content-Type: application/json

### Send DELETE request
DELETE http://localhost:9090/questions/comments/17
Content-Type: application/json

### Send PUT request
PUT http://localhost:9090/questions/3
Content-Type: application/json

{
  "title": "working3",
  "description": "yes3"
}

### Send PUT request
PUT http://localhost:9090/questions/comments/9
Content-Type: application/json

{
  "comment": "checking11111"
}

###





