### Send POST request with json body
POST http://localhost:9090/questions
Content-Type: application/json

{
  "title": "вопрос 5",
  "description": "вопрос номер 5 в схеме stack"
}

### Send POST request with json body
POST http://localhost:9090/questions/4/comments
Content-Type: application/json

{
  "comment": "тест коммент 44444"
}

### Send DELETE request
DELETE http://localhost:9090/questions/2
Content-Type: application/json

### Send PUT request
PUT http://localhost:9090/questions
Content-Type: application/json

{
  "id": 3,
  "title": "test update1",
  "description": "working1"
}

### Send PUT request
PUT http://localhost:9090/questions/comments
Content-Type: application/json

{
  "id": 9,
  "comment": "checking"
}

###





